"use client";

import { useRef } from "react";
import { SectionLabel } from "../common/SectionLabel";
import { useGSAPAnimations } from "../../hooks/useGSAP";

export default function GenesisSection({ milestones }) {
  const ref = useRef(null);
  useGSAPAnimations((gsap) => { const steps = ref.current?.querySelectorAll("[data-genesis-step]"); const line = ref.current?.querySelector("[data-genesis-line]"); const tl = gsap.timeline({ scrollTrigger: { trigger: ref.current, start: "top 65%", end: "bottom 70%", scrub: 0.6 } }); tl.fromTo(line, { scaleX: 0 }, { scaleX: 1, ease: "none", duration: 1 }).fromTo(steps, { autoAlpha: 0.25, x: 36 }, { autoAlpha: 1, x: 0, duration: 0.9, stagger: 0.22, ease: "power2.out" }, 0.1).fromTo(ref.current?.querySelectorAll("[data-genesis-node]"), { scale: 0.1 }, { scale: 1, stagger: 0.22, duration: 0.45, ease: "back.out(2)" }, 0.13); }, { scope: ref, dependencies: [milestones] });
  return <section ref={ref} id="genesis" className="bg-surface section-x section-y"><div className="mx-auto max-w-7xl"><div className="grid gap-10 border-b border-white/10 pb-14 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><div><SectionLabel text="The Genesis" /><h2 className="mt-7 font-syne text-[clamp(2rem,6vw,6rem)] font-extrabold uppercase leading-[.84] tracking-[-.06em] text-white">Designed from a higher standard.</h2></div><div className="max-w-2xl pb-1 text-base leading-relaxed text-white/60 md:text-lg"><p>CoreCraft began with an engineering observation: most digital experiences lack robust architecture. We set out to pair performance precision with the craft that makes a product feel distinct.</p><p className="mt-5">We do not simply build websites. We engineer scalable digital environments that reflect the uncompromising standards of the businesses behind them.</p></div></div>
    <div className="relative mt-14 grid gap-10 lg:mt-20 lg:grid-cols-3 lg:gap-12"><div data-genesis-line aria-hidden="true" className="absolute left-0 right-0 top-[5px] hidden h-px origin-left bg-teal/60 lg:block" />{milestones.map((item) => <article data-genesis-step key={item.name} className="relative border-t border-white/10 pt-7 lg:border-0 lg:pt-12"><span data-genesis-node aria-hidden="true" className="absolute -top-[1px] left-0 hidden h-3 w-3 bg-teal shadow-[0_0_20px_rgba(0,230,217,.8)] lg:block" /><p className="font-mono text-[11px] uppercase tracking-[.2em] text-teal">{item.year}</p><h3 className="mt-6 font-syne text-3xl font-bold uppercase text-white sm:text-4xl">{item.name}</h3><p className="mt-5 max-w-sm text-base leading-relaxed text-white/60">{item.desc}</p></article>)}</div>
  </div></section>;
}
